### ISSUE TITLE
Edda kraschar vid start

### ISSUE THREAD

**Issue by dasovm** [ericwenn/local-feud#78]
### Krasch vid start av Edda.

Får NullPointer på FeedFragment. NullPointer ges på [denna](https://github.com/ericwenn/local-feud/blob/development/project/app/src/main/java/com/chalmers/tda367/localfeud/control/post/FeedFragment.java#L51) rad trots att activity initieras i newInstance.

`05-15 17:25:20.931 655-655/com.chalmers.tda367.localfeud E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.chalmers.tda367.localfeud, PID: 655
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chalmers.tda367.localfeud/com.chalmers.tda367.localfeud.control.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentManager com.chalmers.tda367.localfeud.control.MainActivity.getSupportFragmentManager()' on a null object reference
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

**Comment by ericwenn** [comment]
Mycket mysko. Kan det ha att göra med att man stänger mail activity med finish någonstans? Typ om det inte finns några posts kastas nullpointer och vi kallar på finish i mainactivity

**Comment by dasovm** [comment]
@ericwenn tror det handlar om [setRetainInstance](https://github.com/ericwenn/local-feud/blob/development/project/app/src/main/java/com/chalmers/tda367/localfeud/control/post/FeedFragment.java#L45) då det är omöjligt att activity skulle vara null efter newInstance
